### ISSUE TITLE
Can't get the dataset "Lung cancer (Ontario)".

### ISSUE THREAD

**Issue by Sier-xyt** [tmadl/semisup-learn#5]
When running the example.py,it shows like that:

urllib2.HTTPError: HTTP Error 404: Dataset 'lung-cancer-ontario' not found on mldata.org.

**Comment by shubhamjn1** [comment]
Yes, I also encountered a similar error. You can try using another dataset for example "heart".

**Comment by sxy77** [comment]
Since the lung-cancer-ontario are not found, I use colon-cancer instead. But I found the following error. I thought it might cause by size of data-set but I don't know how to fix it. Any suggestions please?
Traceback (most recent call last):
  File "D:/semisup-learn-master/examples/example.py", line 23, in <module>
    random_labeled_points = random.sample(np.where(ytrue == 0)[0], labeled_N/2)+\
  File "C:\Python27\lib\random.py", line 325, in sample
    raise ValueError("sample larger than population")
ValueError: sample larger than population

**Comment by tongliuF8** [comment]
Same issue here. Would like to have any help, or workaround to get the data. Thanks!
